name: Java CI with Maven

on:
  push:
    branches:
      - main  # ou outra branch que deseja executar a CI
  pull_request:
    branches:
      - main  # ou outra branch que deseja executar a CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn package
